### ISSUE TITLE
Having quota skips sell day and starts the new quota

### ISSUE THREAD

**Issue by zfbx** [Boxofbiscuits97/QuotaRollover#2]
QuotaRollover v2.4.9
thunderstore 1.48.0
BepInEx 5.4.21.0
Lethal Company version updated as of the day this is posted

It seems that after the most recent update it when you have the quota already met from rollover it skips sell day (0 days remaining) instantly and starts the next quota without mention. Once the rollover amount no longer exceeds the required quota it functions as expected.

Functioning this way screws up selling to be able to use the shop because other days you can't sell at 100%.

Can anyone else replicate this issue or is this potentially related to a mod conflict? I haven't been able to test it without other mods installed

**Comment by Boxofbiscuits97** [comment]
I am currently working on a fix that should resolve this right now. I need testers to make sure it works. Join the Lethal Modding Discord if you are available.

https://discord.gg/WqNPnbde

**Comment by zfbx** [comment]
It seems like https://github.com/Boxofbiscuits97/QuotaRollover/commit/5f43edc95a4cca7cd2b1766e4e2cb1e46f5a3039 solved the issue :) thank you and also for the mod <3
